server:
    port: 11999

#spring:
#    datasource:
#        url: jdbc:mysql://123.206.86.173:3306/luway?useSSL=false
#        username: root
#        password: 123456
#        driver-class-name: com.mysql.jdbc.Driver

#eureka:
#    client:
#        service-url:
#            defaultZone: http://localhost:11211/eureka/
#        healthcheck:
#            enabled: true
#        instance:
#            lease-expiration-duration-in-seconds: 30
#        lease-renewal-interval-in-seconds: 30